app:
  replicaCount: 1

  image:
    repository: grafana/tns-app
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: NodePort
    port: 80

  resources: {}

  livenessProbe:
    httpGet:
      path: /
      port: http-metrics
  readinessProbe:
    httpGet:
      path: /
      port: http-metrics

  nodeSelector: {}

  tolerations: []

  affinity: {}

db:
  replicaCount: 1

  image:
    repository: grafana/tns-db
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  resources: {}

  livenessProbe:
    httpGet:
      path: /
      port: http-metrics
  readinessProbe:
    httpGet:
      path: /
      port: http-metrics

  nodeSelector: {}

  tolerations: []

  affinity: {}

loadgen:
  replicaCount: 1

  image:
    repository: grafana/tns-loadgen
    pullPolicy: IfNotPresent
    tag: "latest"

  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""

  podAnnotations: {}
  podLabels: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 80

  resources: {}

  livenessProbe:
    httpGet:
      path: /
      port: http-metrics
  readinessProbe:
    httpGet:
      path: /
      port: http-metrics

  nodeSelector: {}

  tolerations: []

  affinity: {}
