apiVersion: v1
kind: Service
metadata:
  name: {{ include "tns-helm-chart.fullname" . }}-loadgen
  labels:
    {{- include "tns-helm-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loadgen.service.type }}
  ports:
    - port: {{ .Values.loadgen.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "tns-helm-chart.selectorLabels" . | nindent 4 }}
